{{- if .Values.istio.virtualservices.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "demoapi.fullname" . }}
  labels:
    app: {{ template "demoapi.name" . }}
    chart: {{ template "demoapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  gateways:
  {{- range $key, $value := .Values.istio.virtualservices.gateways }}
  - {{ $value }}
  {{- end }}
  hosts:
  {{- range $key, $value := .Values.istio.virtualservices.hosts }}
  - {{ $value }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.virtualservices.apiPath }}
    route:
    - destination:
        host:  {{ template "demoapi.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}          
