{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "atividade02.serviceAccountName" . }}
  labels:
{{ include "atividade02.labels" . | indent 4 }}
{{- end -}}
