{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "firstwebapp.serviceAccountName" . }}
  labels:
{{ include "firstwebapp.labels" . | indent 4 }}
{{- end -}}
