{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exemplo_02.serviceAccountName" . }}
  labels:
{{ include "exemplo_02.labels" . | indent 4 }}
{{- end -}}
