{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "volume-test.serviceAccountName" . }}
  labels:
{{ include "volume-test.labels" . | indent 4 }}
{{- end -}}
