apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-service
  name: wordpress
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: wordpress
  type: LoadBalancer
