apiVersion: v1
kind: Service
metadata:
  name: mysql-service 
  labels:
    tier: service

spec:
  type: ClusterIP
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
