apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env: 
          - name: WORDPRESS_DB_HOST
            value: mysql-service:3306
          - name: WORDPRESS_DB_PASSWORD
            value: minhasenha
        ports: 
          - name: http-port
            containerPort: 80 
