{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ngnix-example.serviceAccountName" . }}
  labels:
{{ include "ngnix-example.labels" . | indent 4 }}
{{- end -}}
